# This is a basic workflow to help you get started with Actions

name: deployment

# Controls when the workflow will run
on:
  push:
    branches:
      - prod
# Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  Login:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

  dateinprod:
    needs: Login
    runs-on: ubuntu-latest
    environment:
      name: prod
    steps:
      # Runs a single command using the runners shell
      - name: Show date
        run: date